name: VelioraWar
version: '1.0.1'
main: id.veliora.war.VelioraWarPlugin
api-version: '1.21'
author: XandMe
description: PvP arena minigame untuk Veliora Gardens
website: https://github.com/XandMe-HX/VelioraWar

softdepend:
  - VelioraSuite

commands:
  vgwar:
    description: Membuka menu dan mengelola VelioraWar
    usage: /vgwar
    aliases: [war, vw]

permissions:
  veliorawar.use:
    description: Membuka GUI VelioraWar
    default: true
  veliorawar.admin:
    description: Mengelola arena dan konfigurasi VelioraWar
    default: op
